#include "MusicBGM.h"
#include "SoundFX.h"
#include <stdio.h>
#include <stdlib.h>
#include <string>

#include <asndlib.h>
#include <mp3player.h>
#include <ogc/lwp.h>
#include <unistd.h>   // usleep
#include <ogc/system.h> // SYS_Report
#include <ogc/audio.h>  // AUDIO_GetDMABytesLeft

/* Embedded MP3 data (generated by xxd from data/music.mp3) */
extern unsigned char data_music_mp3[];
extern unsigned int  data_music_mp3_len;

/* what plays: the built-in music, or the SD card's */
static const unsigned char* s_bgm    = data_music_mp3;
static unsigned int         s_bgmLen = 0;   /* 0: data_music_mp3_len */
#define BGM_DATA s_bgm, (s32)(s_bgmLen ? s_bgmLen : data_music_mp3_len)

static lwp_t         s_thread      = LWP_THREAD_NULL;
static volatile bool s_running     = false;
static bool          s_asndRunning = false; /* true while ASND_Init has been called and ASND_End has not */
static u8            s_stack[16 * 1024] ATTRIBUTE_ALIGN(32);

/* --- MP3Player_Stop with timeout ---
 * MP3Player_Stop can deadlock when the ASND DMA callback state is
 * inconsistent after multiple play/pause cycles.  Run it in a disposable
 * thread and abandon it after 500 ms if it hasn't returned. */
static volatile bool s_stopDone = false;
static u8 s_stopStack[4 * 1024] ATTRIBUTE_ALIGN(32);

static void* stopThreadFunc(void*) {
    MP3Player_Stop();
    s_stopDone = true;
    return nullptr;
}

static void mp3PlayerStopSafe() {
    s_stopDone = false;
    lwp_t t = LWP_THREAD_NULL;
    if (LWP_CreateThread(&t, stopThreadFunc, nullptr,
                         s_stopStack, sizeof(s_stopStack), 80) != 0) {
        /* Thread creation failed — try direct call as fallback */
        SYS_Report("[DBG] mp3PlayerStopSafe: thread create failed, direct call\n");
        MP3Player_Stop();
        return;
    }
    /* Poll for completion with 500 ms timeout (25 × 20 ms) */
    for (int i = 0; i < 25 && !s_stopDone; ++i)
        usleep(20000);
    if (s_stopDone) {
        LWP_JoinThread(t, nullptr);
        SYS_Report("[DBG] mp3PlayerStopSafe: completed normally\n");
    } else {
        SYS_Report("[DBG] mp3PlayerStopSafe: TIMEOUT — abandoning stuck thread\n");
        /* Thread is leaked but we avoid the freeze.  The abandoned thread
         * will eventually return when ASND_End() tears down the DSP. */
    }
}

static void* musicLoop(void*) {
    SYS_Report("[DBG] musicLoop: started, s_running=%d\n", (int)s_running);
    while (s_running) {
        if (!MP3Player_IsPlaying()) {
            SYS_Report("[DBG] musicLoop: PlayBuffer buf=%p len=%u\n",
                       s_bgm, s_bgmLen ? s_bgmLen : data_music_mp3_len);
            MP3Player_PlayBuffer(BGM_DATA, nullptr);
            SYS_Report("[DBG] musicLoop: PlayBuffer done, IsPlaying=%d\n",
                       (int)MP3Player_IsPlaying());
        }
        usleep(200000); /* poll every 200 ms */
    }
    SYS_Report("[DBG] musicLoop: exiting\n");
    return nullptr;
}

void MusicBGM::init(bool startPlaying) {
    SYS_Report("[DBG] MusicBGM::init startPlaying=%d\n", (int)startPlaying);
    ASND_Init();
    ASND_Pause(0);     /* ASND_Init first-time path sets global_pause=1.
                        * MP3Player_Init calls ASND_Pause(0) only on its
                        * very first invocation (init_done guard) so after
                        * an ASND_End()+ASND_Init() cycle the unpause is
                        * never issued — all voices stay silent.  Force it. */
    SYS_Report("[DBG] ASND_Init() done, DMABytesLeft=%u\n",
               (unsigned)AUDIO_GetDMABytesLeft());
    s_asndRunning = true;
    MP3Player_Init();
    if (startPlaying) {
        s_running = true;
        MP3Player_PlayBuffer(BGM_DATA, nullptr);
        SYS_Report("[DBG] MusicBGM::init PlayBuffer done, IsPlaying=%d DMABytesLeft=%u\n",
                   (int)MP3Player_IsPlaying(), (unsigned)AUDIO_GetDMABytesLeft());
        LWP_CreateThread(&s_thread, musicLoop, nullptr, s_stack, sizeof(s_stack), 80);
    }
}

void MusicBGM::stop() {
    SYS_Report("[DBG] MusicBGM::stop ENTER running=%d thread=%p asnd=%d\n",
               (int)s_running, (void*)s_thread, (int)s_asndRunning);
    s_running = false;
    if (s_thread != LWP_THREAD_NULL) {
        LWP_JoinThread(s_thread, nullptr);
        s_thread = LWP_THREAD_NULL;
    }
    mp3PlayerStopSafe();
    if (s_asndRunning) {
        ASND_End();
        s_asndRunning = false;
    }
    SYS_Report("[DBG] MusicBGM::stop EXIT\n");
}

void MusicBGM::pause() {
    SYS_Report("[DBG] MusicBGM::pause ENTER running=%d thread=%p asnd=%d\n",
               (int)s_running, (void*)s_thread, (int)s_asndRunning);
    if (!s_running && s_thread == LWP_THREAD_NULL) {
        /* Already fully stopped — but ASND may still be running from a
         * previous resume() or init().  Shut it down so ao_gekko can take
         * over the AI DMA without conflict.  Do NOT call it twice if it is
         * already ended (double-End corrupts the DSP interrupt handler). */
        SYS_Report("[DBG] MusicBGM::pause early path: mp3PlayerStopSafe...\n");
        mp3PlayerStopSafe();
        if (s_asndRunning) {
            SYS_Report("[DBG] MusicBGM::pause early path: ASND_End...\n");
            SoundFX::fadeOut();
            ASND_End();
            SYS_Report("[DBG] MusicBGM::pause early path: ASND_End done\n");
            s_asndRunning = false;
        }
        SYS_Report("[DBG] MusicBGM::pause EXIT (early) asnd=%d\n", (int)s_asndRunning);
        return;
    }
    SYS_Report("[DBG] MusicBGM::pause: setting s_running=false\n");
    s_running = false;
    if (s_thread != LWP_THREAD_NULL) {
        SYS_Report("[DBG] MusicBGM::pause: LWP_JoinThread ENTER thread=%p\n", (void*)s_thread);
        LWP_JoinThread(s_thread, nullptr);
        s_thread = LWP_THREAD_NULL;
        SYS_Report("[DBG] MusicBGM::pause: LWP_JoinThread DONE\n");
    }
    SYS_Report("[DBG] MusicBGM::pause: mp3PlayerStopSafe...\n");
    mp3PlayerStopSafe();
    if (s_asndRunning) {
        SYS_Report("[DBG] MusicBGM::pause: ASND_End...\n");
        SoundFX::fadeOut();
        ASND_End();          /* Fully shut down ASND's internal DSP thread and its
                              * AI DMA callback so ao_gekko can take over DMA
                              * without conflict.  resume() re-calls ASND_Init(). */
        SYS_Report("[DBG] MusicBGM::pause: ASND_End done\n");
        s_asndRunning = false;
    }
    SYS_Report("[DBG] MusicBGM::pause EXIT asnd=%d running=%d\n", (int)s_asndRunning, (int)s_running);
}

void MusicBGM::resume() {
    SYS_Report("[DBG] MusicBGM::resume ENTER asnd=%d running=%d thread=%p self=%p\n",
               (int)s_asndRunning, (int)s_running, (void*)s_thread,
               (void*)(uintptr_t)LWP_GetSelf());
    if (s_asndRunning) {   /* pause() normally ended it: never end ASND twice */
        ASND_End();
        s_asndRunning = false;
    }
    ASND_Init();
    ASND_Pause(0);     /* See comment in init() — must unpause after reinit */
    s_asndRunning = true;
    MP3Player_Init();
    s_running = true;
    SYS_Report("[DBG] MusicBGM::resume: PlayBuffer buf=%p len=%u\n",
               s_bgm, s_bgmLen ? s_bgmLen : data_music_mp3_len);
    MP3Player_PlayBuffer(BGM_DATA, nullptr);
    SYS_Report("[DBG] MusicBGM::resume: PlayBuffer done, IsPlaying=%d\n",
               (int)MP3Player_IsPlaying());
    LWP_CreateThread(&s_thread, musicLoop, nullptr, s_stack, sizeof(s_stack), 80);
    SYS_Report("[DBG] MusicBGM::resume EXIT thread=%p\n", (void*)s_thread);
}

void MusicBGM::reinitAudio() {
    SYS_Report("[DBG] MusicBGM::reinitAudio ENTER asnd=%d\n", (int)s_asndRunning);
    if (!s_asndRunning) {
        SYS_Report("[DBG] ASND_Init() called @ MusicBGM::reinitAudio\n");
        ASND_Init();
        ASND_Pause(0);     /* See comment in init() — must unpause after reinit */
        s_asndRunning = true;
    }
    MP3Player_Init();
    SYS_Report("[DBG] MusicBGM::reinitAudio EXIT\n");
}

/* The music alone (Settings, the HOME menu): pause() also ends ASND for
 * MPlayer, and the interface sounds went silent with it until the next
 * video.  ASND is left as it is: on in the menus, off during a video. */
void MusicBGM::stopMusic() {
    s_running = false;
    if (s_thread != LWP_THREAD_NULL) {
        LWP_JoinThread(s_thread, nullptr);
        s_thread = LWP_THREAD_NULL;
    }
    if (s_asndRunning && MP3Player_IsPlaying()) mp3PlayerStopSafe();
}

void MusicBGM::setEnabled(bool on) {
    if (on && !s_running)  resume();
    else if (!on)          stopMusic();
}

bool MusicBGM::isRunning() {
    return s_running;
}

bool MusicBGM::audioOn() {
    return s_asndRunning;
}

/* At most 16 MB: the whole file stays in memory (MP3Player plays from a
 * buffer); 16 MB of MP3 is about 15 minutes at 128 kb/s */
void MusicBGM::loadCustom(const char* dir) {
    if (!dir || !*dir) return;
    std::string path = std::string(dir) + "sounds/bgm.mp3";
    FILE* f = fopen(path.c_str(), "rb");
    if (!f) return;
    fseek(f, 0, SEEK_END);
    long size = ftell(f);
    fseek(f, 0, SEEK_SET);
    if (size <= 0 || size > (16L << 20)) {
        SYS_Report("[Sound] bgm.mp3: %ld bytes, at most 16 MB: built-in music kept\n", size);
    } else if (unsigned char* buf = (unsigned char*)malloc((size_t)size)) {
        if (fread(buf, 1, (size_t)size, f) == (size_t)size) {
            s_bgm    = buf;
            s_bgmLen = (unsigned)size;
            SYS_Report("[Sound] bgm.mp3 from the SD card (%ld KB)\n", size / 1024);
        } else {
            free(buf);
        }
    }
    fclose(f);
}
