#include "SoundFX.h"
#include "MusicBGM.h"

#include <mad.h>
#include <asndlib.h>
#include <ogc/cache.h>
#include <ogc/lwp_watchdog.h>
#include <malloc.h>
#include <string.h>
#include <stdint.h>
#include <unistd.h>
#include <stdio.h>
#include <string>
#include <vector>
#include <algorithm>
#include <ogc/system.h>   // SYS_Report

/* -----------------------------------------------------------------------
 * Embedded MP3 data (generated by xxd in the Makefile)
 * ----------------------------------------------------------------------- */
extern unsigned char data_sounds_start_mp3[];
extern unsigned int  data_sounds_start_mp3_len;
extern unsigned char data_sounds_select_mp3[];
extern unsigned int  data_sounds_select_mp3_len;
extern unsigned char data_sounds_press_key_mp3[];
extern unsigned int  data_sounds_press_key_mp3_len;
extern unsigned char data_sounds_menu_exit_mp3[];
extern unsigned int  data_sounds_menu_exit_mp3_len;
extern unsigned char data_sounds_menu_enter_mp3[];
extern unsigned int  data_sounds_menu_enter_mp3_len;
extern unsigned char data_sounds_loading_mp3[];
extern unsigned int  data_sounds_loading_mp3_len;
extern unsigned char data_sounds_backspace_mp3[];
extern unsigned int  data_sounds_backspace_mp3_len;
extern unsigned char data_sounds_back_mp3[];
extern unsigned int  data_sounds_back_mp3_len;

/* -----------------------------------------------------------------------
 * ASND voice slots — keep away from MP3Player which uses voices 0–1.
 * ----------------------------------------------------------------------- */
static const int      FX_VOICES[]     = { 4, 7, 8, 9 }; /* one-shots, several at once */
static const int      LOAD_VOICE      = 5;   /* looping loading sound              */
static const int      MENU_VOICE      = 6;   /* MenuEnter/MenuExit — dedicated slot */
static const int      FX_VOL          = 200; /* 0–255                              */
static const uint64_t FX_COOLDOWN_MS  = 150;  /* minimum interval between same-FX   */

/* Custom sounds: at most this much file, and this long once decoded (the
 * PCM stays in memory: 10 s of 48 kHz stereo is 1.9 MB) */
static const long     CUSTOM_MAX_FILE = 2L << 20;
static const unsigned CUSTOM_MAX_SECS = 10;

static bool s_enabled = true;
static bool s_logging = false;

/* Per-FX last-play timestamp (ms); 0 = never played, so first play always works */
static uint64_t s_fxLastPlayMs[(int)SoundFX::FX::COUNT_] = {};
static int      s_fxVoice[(int)SoundFX::FX::COUNT_] = {};   /* voice it last played on */

/* File names in sounds/ (without .mp3 / .wav), in the order of enum FX */
static const char* const NAMES[(int)SoundFX::FX::COUNT_] = {
    "start", "select", "press_key", "menu_exit", "menu_enter", "loading",
    "backspace", "back", "move", "open", "play", "page",
};

/* The newer FX play an older one's sound unless sounds/ has their own:
 * the same decoded buffer, -1 = a sound of its own */
static const int BUILTIN_AS[(int)SoundFX::FX::COUNT_] = {
    -1, -1, -1, -1, -1, -1, -1, -1,
    (int)SoundFX::FX::Select,   /* Move */
    (int)SoundFX::FX::Start,    /* Open */
    (int)SoundFX::FX::Start,    /* Play */
    (int)SoundFX::FX::Select,   /* Page */
};

/* Per-FX gain applied during PCM decode of the built-in sounds (1.0 =
 * unity; <1.0 = attenuate).  Apply here — before the int16 clamp — so loud
 * sources don't clip.  Order must match enum FX; custom files play as
 * they are. */
static const float FX_GAIN[(int)SoundFX::FX::COUNT_] = {
    0.40f,  /* Start     — source is very loud; reduce to prevent clipping */
    1.0f,   /* Select    */
    1.0f,   /* PressKey  */
    1.0f,   /* MenuExit  */
    1.0f,   /* MenuEnter */
    1.0f,   /* Loading   */
    1.0f,   /* Backspace */
    1.0f,   /* Back      */
    1.0f, 1.0f, 1.0f, 1.0f,   /* Move, Open, Play, Page: BUILTIN_AS */
};

/* -----------------------------------------------------------------------
 * PCM buffer descriptor
 * ----------------------------------------------------------------------- */
struct PcmBuf {
    void*        data;     /* memalign(32) PCM buffer, cache-flushed */
    unsigned int byteLen;  /* byte length of valid PCM data          */
    int          pitch;    /* sample rate in Hz                      */
    int          format;   /* VOICE_STEREO_16BIT or VOICE_MONO_16BIT */
};

static PcmBuf   s_fx[(int)SoundFX::FX::COUNT_] = {};

/* Earliest time (ms) at which tickLoading() is allowed to restart the voice.
 * Computed from the actual decoded buffer duration so the restart is gated on
 * the real playback length, not on ASND's async status flag. */
static uint64_t s_loadReadyMs = 0;

/* -----------------------------------------------------------------------
 * decodeMp3 — decode an MP3 buffer into a 32-byte-aligned PCM buffer
 *             using libmad.  Returns an empty PcmBuf on failure.
 * ----------------------------------------------------------------------- */
static PcmBuf toPcmBuf(const std::vector<int16_t>& tmp, unsigned rate, int channels);

static PcmBuf decodeMp3(const unsigned char* mp3Data, unsigned int mp3Len,
                        float gain = 1.0f, unsigned maxSecs = 0)
{
    /* Pre-compute gain in Q1.28 (same domain as mad_fixed_t = int32_t Q1.28). */
    const mad_fixed_t gainQ28 = (mad_fixed_t)((double)gain * (double)MAD_F_ONE);
    PcmBuf result = {};
    if (!mp3Data || !mp3Len) return result;

    std::vector<int16_t> tmp;
    /* rough upper-bound estimate, within the length kept */
    tmp.reserve(maxSecs ? std::min<size_t>((size_t)mp3Len * 8, (size_t)maxSecs * 48000 * 2)
                        : (size_t)mp3Len * 8);

    struct mad_stream stream;
    struct mad_frame  frame;
    struct mad_synth  synth;
    mad_stream_init(&stream);
    mad_frame_init(&frame);
    mad_synth_init(&synth);

    mad_stream_buffer(&stream, mp3Data, mp3Len);

    unsigned int sampleRate = 44100;
    int          channels   = 2;
    bool         gotHeader  = false;

    for (;;) {
        if (mad_frame_decode(&frame, &stream) == -1) {
            if (stream.error == MAD_ERROR_BUFLEN || !MAD_RECOVERABLE(stream.error))
                break;
            continue;
        }
        if (!gotHeader) {
            sampleRate = frame.header.samplerate;
            channels   = (frame.header.mode == MAD_MODE_SINGLE_CHANNEL) ? 1 : 2;
            gotHeader  = true;
        }
        if (maxSecs && tmp.size() >= (size_t)maxSecs * sampleRate * channels) break;
        mad_synth_frame(&synth, &frame);

        const struct mad_pcm& pcm = synth.pcm;
        for (unsigned int i = 0; i < pcm.length; ++i) {
            /* Left / mono channel */
            mad_fixed_t s = pcm.samples[0][i];
            /* Apply gain before the clamp so loud sources don't saturate. */
            if (gainQ28 != MAD_F_ONE)
                s = (mad_fixed_t)(((int64_t)s * gainQ28) >> MAD_F_FRACBITS);
            if (s >=  MAD_F_ONE) s =  MAD_F_ONE - 1;
            if (s < -MAD_F_ONE)  s = -MAD_F_ONE;
            tmp.push_back((int16_t)(s >> (MAD_F_FRACBITS - 15)));

            /* Right channel (or duplicate left for forced-stereo mono input) */
            if (channels == 2) {
                s = pcm.samples[1][i];
                if (gainQ28 != MAD_F_ONE)
                    s = (mad_fixed_t)(((int64_t)s * gainQ28) >> MAD_F_FRACBITS);
                if (s >=  MAD_F_ONE) s =  MAD_F_ONE - 1;
                if (s < -MAD_F_ONE)  s = -MAD_F_ONE;
                tmp.push_back((int16_t)(s >> (MAD_F_FRACBITS - 15)));
            }
        }
    }

    mad_synth_finish(&synth);
    mad_frame_finish(&frame);
    mad_stream_finish(&stream);

    return toPcmBuf(tmp, sampleRate, channels);
}

/* PCM samples (native order) into a 32-byte-aligned, cache-flushed buffer */
static PcmBuf toPcmBuf(const std::vector<int16_t>& tmp, unsigned rate, int channels)
{
    PcmBuf result = {};
    if (tmp.empty()) return result;

    unsigned int byteLen    = (unsigned int)tmp.size() * sizeof(int16_t);
    unsigned int alignedLen = (byteLen + 31u) & ~31u;
    void* buf = memalign(32, alignedLen);
    if (!buf) return result;

    memset(buf, 0, alignedLen);
    memcpy(buf, tmp.data(), byteLen);
    DCFlushRange(buf, alignedLen); /* ensure DSP sees the data */

    result.data    = buf;
    result.byteLen = byteLen;
    result.pitch   = (int)rate;
    result.format  = (channels == 2) ? VOICE_STEREO_16BIT : VOICE_MONO_16BIT;
    return result;
}

/* A WAV file: PCM, 8 or 16 bits, mono or stereo, up to 48 kHz */
static PcmBuf decodeWav(const unsigned char* d, size_t len, unsigned maxSecs)
{
    auto le16 = [&](size_t o) { return (unsigned)(d[o] | d[o + 1] << 8); };
    auto le32 = [&](size_t o) { return (unsigned)(d[o] | d[o + 1] << 8 | d[o + 2] << 16 | (unsigned)d[o + 3] << 24); };
    if (len < 12 || memcmp(d, "RIFF", 4) || memcmp(d + 8, "WAVE", 4)) return PcmBuf{};
    unsigned fmt = 0, channels = 0, rate = 0, bits = 0;
    for (size_t o = 12; o + 8 <= len; ) {
        unsigned n = le32(o + 4);
        size_t body = o + 8;
        if (!memcmp(d + o, "fmt ", 4) && n >= 16 && body + 16 <= len) {
            fmt = le16(body); channels = le16(body + 2); rate = le32(body + 4); bits = le16(body + 14);
        } else if (!memcmp(d + o, "data", 4)) {
            if (fmt != 1 || (channels != 1 && channels != 2) || (bits != 8 && bits != 16) ||
                rate < 8000 || rate > 48000)
                return PcmBuf{};
            size_t end = std::min(len, body + n);
            size_t step = bits / 8;
            size_t max = (size_t)maxSecs * rate * channels;
            std::vector<int16_t> tmp;
            tmp.reserve(std::min((end - body) / step, max));
            for (size_t i = body; i + step <= end && tmp.size() < max; i += step)
                tmp.push_back(bits == 16 ? (int16_t)le16(i) : (int16_t)((d[i] - 128) << 8));
            return toPcmBuf(tmp, rate, (int)channels);
        }
        o = body + n + (n & 1);
    }
    return PcmBuf{};
}

/* <dir>sounds/<name>.mp3 or .wav, decoded; empty when there is none */
static PcmBuf loadCustom(const std::string& dir, const char* name)
{
    static const char* const EXT[] = { ".mp3", ".wav" };
    for (const char* ext : EXT) {
        std::string path = dir + "sounds/" + name + ext;
        FILE* f = fopen(path.c_str(), "rb");
        if (!f) continue;
        fseek(f, 0, SEEK_END);
        long size = ftell(f);
        fseek(f, 0, SEEK_SET);
        PcmBuf b = {};
        if (size <= 0 || size > CUSTOM_MAX_FILE) {
            SYS_Report("[Sound] %s%s: %ld bytes, at most %ld: built-in sound kept\n",
                       name, ext, size, CUSTOM_MAX_FILE);
        } else {
            std::vector<unsigned char> data((size_t)size);
            if (fread(data.data(), 1, data.size(), f) == data.size())
                b = ext[1] == 'm' ? decodeMp3(data.data(), (unsigned)data.size(), 1.0f, CUSTOM_MAX_SECS)
                                  : decodeWav(data.data(), data.size(), CUSTOM_MAX_SECS);
            if (b.data)
                SYS_Report("[Sound] %s%s from the SD card (%.1f s)\n", name, ext,
                           b.byteLen / (double)(b.pitch * (b.format == VOICE_STEREO_16BIT ? 4 : 2)));
            else
                SYS_Report("[Sound] %s%s: cannot be read (MP3, or WAV PCM 8/16-bit up to 48 kHz): built-in sound kept\n",
                           name, ext);
        }
        fclose(f);
        if (b.data) return b;
    }
    return PcmBuf{};
}

/* -----------------------------------------------------------------------
 * Public API
 * ----------------------------------------------------------------------- */
void SoundFX::init(const char* dir)
{
    const std::string base = dir ? dir : "";
    /* Source table — order must match enum FX { Start, Select, ... } */
    struct Src { const unsigned char* data; unsigned int len; };
    const Src srcs[(int)FX::COUNT_] = {
        { data_sounds_start_mp3,      data_sounds_start_mp3_len      }, /* Start     */
        { data_sounds_select_mp3,     data_sounds_select_mp3_len     }, /* Select    */
        { data_sounds_press_key_mp3,  data_sounds_press_key_mp3_len  }, /* PressKey  */
        { data_sounds_menu_exit_mp3,  data_sounds_menu_exit_mp3_len  }, /* MenuExit  */
        { data_sounds_menu_enter_mp3, data_sounds_menu_enter_mp3_len }, /* MenuEnter */
        { data_sounds_loading_mp3,    data_sounds_loading_mp3_len    }, /* Loading   */
        { data_sounds_backspace_mp3,  data_sounds_backspace_mp3_len  }, /* Backspace */
        { data_sounds_back_mp3,       data_sounds_back_mp3_len       }, /* Back      */
        { nullptr, 0 }, { nullptr, 0 }, { nullptr, 0 }, { nullptr, 0 },   /* BUILTIN_AS */
    };

    for (int i = 0; i < (int)FX::COUNT_; ++i) {
        if (!base.empty()) s_fx[i] = loadCustom(base, NAMES[i]);
        if (s_fx[i].data) continue;   /* a custom sound: no trim, as it is */
        if (BUILTIN_AS[i] >= 0) {     /* decoded and trimmed already (earlier in the table) */
            s_fx[i] = s_fx[BUILTIN_AS[i]];
            continue;
        }
        s_fx[i] = decodeMp3(srcs[i].data, srcs[i].len, FX_GAIN[i]);

        /* Trim leading silence (MP3 encoder pre-roll padding, typically ~13 ms
         * of mathematically exact zeros produced by LAME).
         * Use a low -48 dB threshold (|v| >= 128) so that only true encoder
         * silence is skipped — sounds with soft attacks (e.g. menu_exit) are
         * preserved from the first audible sample.  A -24 dB threshold was
         * previously used but it cut 8–9 ms of actual soft-attack content.
         * Step back 8 samples to keep the transient, then round down to a
         * 32-byte cache-line boundary. */
        PcmBuf& b = s_fx[i];
        if (b.data && b.byteLen >= 64) {
            const int16_t* pcm   = (const int16_t*)b.data;
            unsigned int   n     = b.byteLen / sizeof(int16_t);
            unsigned int   first = 0; /* stays 0 if no silence found */
            for (unsigned int s = 0; s < n; ++s) {
                if (pcm[s] > 128 || pcm[s] < -128) {
                    first = (s > 8) ? s - 8 : 0;
                    break;
                }
            }
            unsigned int skip = (first * (unsigned int)sizeof(int16_t)) & ~31u;
            if (skip > 0 && skip < b.byteLen) {
                /* memalign'ed start kept by the aliases (BUILTIN_AS) as is */
                b.data    = (uint8_t*)b.data + skip;
                b.byteLen -= skip;
                /* Re-flush so the DSP DMA reads from the new aligned start. */
                DCFlushRange(b.data, (b.byteLen + 31u) & ~31u);
            }
        }
    }
}

void SoundFX::setEnabled(bool on) { s_enabled = on; if (!on) stopLoading(); }
bool SoundFX::enabled()          { return s_enabled; }
void SoundFX::setLogging(bool on) { s_logging = on; }

void SoundFX::play(FX fx)
{
    int idx = (int)fx;
    if (idx < 0 || idx >= (int)FX::COUNT_) return;
    /* ASND is shut down while MPlayer plays: nothing to play on */
    if (!s_enabled || !MusicBGM::audioOn()) return;

    const PcmBuf& b = s_fx[idx];
    if (!b.data || !b.byteLen) return;

    if (s_logging) SYS_Report("[Sound] %s\n", NAMES[idx]);
    if (fx == FX::Loading) {
        /* Arm the loop — actual playback starts (and re-starts) via tickLoading(). */
        ASND_StopVoice(LOAD_VOICE);
        s_loadReadyMs = 0; /* allow tickLoading() to fire immediately */
    } else {
        uint64_t nowMs = ticks_to_millisecs(gettime());

        /* MenuEnter and MenuExit use their own dedicated voice so they are
         * never dropped because FX_VOICE is busy with a hover/key sound.
         * They are also exempt from the cooldown so the sound always plays
         * even if the menu is opened/closed rapidly. */
        const bool  isMenu = (fx == FX::MenuEnter || fx == FX::MenuExit);

        /* Per-FX cooldown: skip if this exact sound played recently.
         * Prevents rapid-hover spam and back-to-back retrigger glitches.
         * Not applied to menu sounds which must always play. */
        if (!isMenu) {
            if (nowMs - s_fxLastPlayMs[idx] < FX_COOLDOWN_MS) return;
            s_fxLastPlayMs[idx] = nowMs;
        }
        /* A free one-shot voice, so that a sound never waits for the one
         * before it (moving through a list plays one per step); the first
         * one when they are all busy. */
        int voice = MENU_VOICE;
        if (!isMenu) {
            voice = FX_VOICES[0];
            for (int v : FX_VOICES)
                if (ASND_StatusVoice(v) == SND_UNUSED) { voice = v; break; }
        }
        s_fxVoice[idx] = voice;

        /* Stop the voice, then spin-wait for ASND to reach SND_UNUSED.
         * ASND_StopVoice is asynchronous — the DSP processes it on its next
         * callback (~5 ms).  If ASND_SetVoice is called while the voice is
         * still in SND_STOPPING it returns SND_BUSY and silently discards the
         * play request — causing the "sound doesn't start" symptom.
         * 40 × 500 µs = 20 ms maximum wait; always well within one frame. */
        ASND_StopVoice(voice);
        for (int i = 0; i < 40 && ASND_StatusVoice(voice) != SND_UNUSED; i++)
            usleep(500);

        ASND_SetVoice(voice, b.format, b.pitch, 0,
                      b.data, (int)b.byteLen, FX_VOL, FX_VOL, nullptr);
    }
}

void SoundFX::waitDone(FX fx)
{
    if (!s_enabled || !MusicBGM::audioOn()) return;
    const bool isMenu = (fx == FX::MenuEnter || fx == FX::MenuExit);
    const int  voice  = isMenu ? MENU_VOICE : (s_fxVoice[(int)fx] ? s_fxVoice[(int)fx] : FX_VOICES[0]);
    /* ASND_SetVoice is asynchronous — give the DSP one callback cycle (~5 ms)
     * to actually start the voice before we start polling for idle. */
    usleep(30000);
    /* Then spin-wait up to ~1 s (200 × 5 ms) for playback to finish. */
    for (int i = 0; i < 200 && ASND_StatusVoice(voice) != SND_UNUSED; i++)
        usleep(5000);
}

void SoundFX::tickLoading()
{
    if (!s_enabled || !MusicBGM::audioOn()) return;
    const PcmBuf& b = s_fx[(int)FX::Loading];
    if (!b.data || !b.byteLen || !b.pitch) return;

    /* Gate: don't restart before the buffer has had time to finish.
     * ASND_SetVoice is asynchronous — StatusVoice can still read SND_UNUSED
     * for one or more frames after the call, causing a rapid-restart loop.
     * We compute the exact duration from the buffer size and only allow a
     * restart once that wall-clock time has elapsed. */
    uint64_t nowMs = ticks_to_millisecs(gettime());
    if (nowMs < s_loadReadyMs) return;

    /* Also confirm the voice is actually idle before touching it. */
    if (ASND_StatusVoice(LOAD_VOICE) != SND_UNUSED) return;

    /* Compute duration and schedule the next earliest restart. */
    int      bps      = (b.format == VOICE_STEREO_16BIT) ? 4 : 2;
    uint64_t durMs    = ((uint64_t)b.byteLen * 1000ULL)
                        / ((uint64_t)b.pitch * (uint64_t)bps);
    s_loadReadyMs = nowMs + durMs;

    ASND_SetVoice(LOAD_VOICE, b.format, b.pitch, 0,
                  b.data, (int)b.byteLen, FX_VOL, FX_VOL, nullptr);
}

void SoundFX::stopLoading()
{
    if (MusicBGM::audioOn()) ASND_StopVoice(LOAD_VOICE);
}

/* ASND_End cuts a sound mid-wave, which clicks: 40 ms down to silence
 * first (the click of a video's start, say) */
void SoundFX::fadeOut()
{
    if (!MusicBGM::audioOn()) return;
    static const int VOICES[] = { 4, 5, 6, 7, 8, 9 };
    bool any = false;
    for (int v : VOICES) any |= ASND_StatusVoice(v) != SND_UNUSED;
    if (!any) return;
    for (int step = 7; step >= 0; --step) {
        for (int v : VOICES)
            if (ASND_StatusVoice(v) != SND_UNUSED)
                ASND_ChangeVolumeVoice(v, FX_VOL * step / 8, FX_VOL * step / 8);
        usleep(5000);
    }
    for (int v : VOICES) ASND_StopVoice(v);
}
